#!/bin/bash
## Do not allow commits with debug statements or git
FILES_PATTERN='\.(js)(\..+)?$'
FORBIDDEN="\b(console\.debug|debug|console\.log|debugger|<<<<<<<|>>>>>>>)\b"
git diff-index -p --cached --diff-filter=ACMRTUXB -G"${FORBIDDEN}" HEAD | \
  grep "^+[^+]" | \
  GREP_COLOR='37;41' grep --color -E $FORBIDDEN && echo "\nError: Found some debug-looking code. Please remove it before committing (use \"git commit --no-verify...\" to skip).\n" && exit 1

git status -s | cut -c4- | grep '\.js$' | xargs ./node_modules/.bin/eslint --fix

#!/usr/bin/env bash


# Place `ENFORCERY_DOCKER=true` in your shell profile to run this script inside
# the application docker container. This will allow the pre-commit hook to run
# in a clean docker development environment where the gems are not locally
# bundled.
if [[ $ENFORCERY_DOCKER == 'true' ]]; then
  docker-compose run --rm web hooks/pre-commit
  exit $?
fi

# Do not allow commits with debug statements or git
# FILES_PATTERN='\.(js|rb)(\..+)?$'
# FORBIDDEN="\b(console\.debug|byebug|debug|console\.log|debugger|puts|pp|<<<<<<<|>>>>>>>|(if|unless).?.?.?(true|false))\b"
# git diff-index -p --cached --diff-filter=ACMRTUXB -G"${FORBIDDEN}" HEAD | \
#   grep "^+[^+]" | \
#   GREP_COLOR='37;41' grep --color -E $FORBIDDEN && echo "\nError: Found some debug-looking code. Please remove it before committing (use \"git commit --no-verify...\" to skip).\n" && exit 1

JSHINT='./node_modules/.bin/jshint'
JSCS='./node_modules/.bin/jscs'

# Run Rubocop on any changed files
CHANGED_RUBY_FILES=`git diff --cached --diff-filter=ACMRTUXB --name-only | grep '\.rb$'`
if [[ $CHANGED_RUBY_FILES ]] && ! bundle exec rubocop -D --force-exclusion $CHANGED_RUBY_FILES; then
  echo "\n[■_■] Rubocop is not happy. Please clean things up before committing (or use \"git commit --no-verify...\" to skip).\n" && exit 1
fi

CHANGED_SCSS_FILES=`git diff --cached --diff-filter=ACMRTUXB --name-only | grep '\.scss$'`
if [[ $CHANGED_SCSS_FILES ]]; then
  # scss-lint exits with a 66 if no files are found. This may happen when a file changes
  # that is on "exclude" list in .scss-lint.yml
  bundle exec scss-lint $CHANGED_SCSS_FILES
  if [ $? -ne 0 -a $? -ne 66 ]; then
    echo "\n[■_■] SCSS-Lint is not happy. Please clean things up before committing (or use \"git commit --no-verify...\" to skip).\n" && exit 1
  fi
fi

CHANGED_JAVASCRIPT_FILES=`git diff --cached --diff-filter=ACMRTUXB --name-only | grep '\.js$'`
if [[ $CHANGED_JAVASCRIPT_FILES ]] && which $JSHINT && ! $JSHINT app/assets/javascripts/backbone/ app/assets/javascripts/ctly-ui/; then
  echo "\n[■_■] JSHint is not happy. Please clean things up before committing (or use \"git commit --no-verify...\" to skip).\n" && exit 1
fi

if [[ $CHANGED_JAVASCRIPT_FILES ]] && which $JSCS && ! $JSCS --verbose app/assets/javascripts/backbone/ app/assets/javascripts/ctly-ui/; then
  echo "\n[■_■] JSCS is not happy. Please clean things up before committing (or use \"git commit --no-verify...\" to skip).\n" && exit 1
fi

exit 0
