#!/bin/sh

# local_hook="$HOME"/.git_template.local/hooks/prepare-commit-msg
#
# if [ -f "$local_hook" ]; then
#   . "$local_hook"
# fi

# This way you can customize which branches should be skipped when
# prepending commit message.
# if [ -z "$BRANCHES_TO_SKIP" ]; then
#   BRANCHES_TO_SKIP=(master)
# fi
#
# BRANCH_NAME=$(git symbolic-ref --short HEAD)
# BRANCH_NAME="${BRANCH_NAME:\s*/}"
#
# BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
# BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)
#
# if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
#   sed -i.bak -e "1s/^/$BRANCH_NAME: /" $1
